services:
  quick-list-app:
    networks:
      - quicklist-net
  database:
    image: postgres:latest
    env_file:
      - ./.env
    networks:
      - quicklist-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  quicklist-net: